{
    "attributes": {
        "entityScope": {
            "allowed_choices": [
                "ENTERPRISE", 
                "GLOBAL"
            ], 
            "autogenerated": true, 
            "description": "Specify if scope of entity is Data center or Enterprise level", 
            "exposed": true, 
            "filterable": false,
            "format": "free", 
            "orderable": false,
            "type": "enum", 
            "uniqueScope": "no"
        }, 
        "externalID": {
            "description": "External object ID. Used for integration with third party systems", 
            "exposed": true, 
            "filterable": true, 
            "format": "free", 
            "orderable": true, 
            "type": "string", 
            "unique": true, 
            "uniqueScope": "no"
        }
    }
}