{
    "attributes": {
        "entityScope": {
            "description": "Specify if scope of entity is Data center or Enterprise level", 
            "format": "free", 
            "filterable": true, 
            "autogenerated": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "allowed_choices": [
                "ENTERPRISE", 
                "GLOBAL"
            ], 
            "orderable": true, 
            "type": "enum"
        }, 
        "lastUpdatedBy": {
            "required": true, 
            "description": "ID of the user who last updated the object.", 
            "format": "free", 
            "filterable": true, 
            "autogenerated": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "externalID": {
            "description": "External object ID. Used for integration with third party systems", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "unique": true, 
            "type": "string"
        }
    }, 
    "model": {}
}