{
    "attributes": {
        "description": {
            "description": "Description of the alarm", 
            "format": "free", 
            "filterable": true, 
            "uniqueScope": "no", 
            "required": true, 
            "exposed": true, 
            "orderable": true, 
            "type": "string"
        }, 
        "severity": {
            "description": "Severity of the alarm.  Possible values are MAJOR, MINOR, CRITICAL, INFO, WARNING, .", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "allowed_choices": [
                "MINOR", 
                "MAJOR", 
                "WARNING", 
                "CRITICAL", 
                "INFO"
            ], 
            "orderable": true, 
            "type": "enum"
        }, 
        "acknowledged": {
            "description": "Flag to indicate that alarm is already acknowledged or not", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "boolean"
        }, 
        "reason": {
            "description": "Provides a description of the alarm", 
            "format": "free", 
            "filterable": true, 
            "uniqueScope": "no", 
            "required": true, 
            "exposed": true, 
            "orderable": true, 
            "type": "string"
        }, 
        "errorCondition": {
            "description": "Identifies the error condition", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "integer"
        }, 
        "enterpriseID": {
            "description": "Enterprise that this alarm belongs to", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "targetObject": {
            "description": "Identifies affected Entity.  Example: Alarm generated by TCA for Domain domain1(Packets towards a VM, Breach)", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "timestamp": {
            "description": "Indicates the time that the alarm was triggered", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "float"
        }, 
        "numberOfOccurances": {
            "description": "Number of times that the alarm was triggered", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "integer"
        }, 
        "name": {
            "description": "The alarm name.  Each type of alarm will generate its own name", 
            "format": "free", 
            "filterable": true, 
            "uniqueScope": "no", 
            "required": true, 
            "exposed": true, 
            "orderable": true, 
            "type": "string"
        }
    }, 
    "model": {
        "resource_name": "alarms", 
        "description": "The alarm API allows the management of system alarms.", 
        "entity_name": "Alarm", 
        "package": "alarm", 
        "get": true, 
        "update": true, 
        "rest_name": "alarm", 
        "extends": [
            "@base", 
            "@metadata"
        ], 
        "delete": true
    }
}