{
    "apis": {
        "children": {},
        "parents": {
            "/enterprises/{id}/applicationservices": {
                "RESTName": "enterprise",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    }],
                "resourceName": "enterprises"
            },
            "/prout/{id}/applicationservices": {
                "RESTName": "enterprise",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    }],
                "resourceName": "enterprises"
            }
        },
        "self": {
            "/applicationservices/{id}": {
                "RESTName": "applicationservice",
                "operations": [
                    {
                        "availability": null,
                        "method": "PUT"
                    },
                    {
                        "availability": null,
                        "method": "DELETE"
                    },
                    {
                        "availability": null,
                        "method": "GET"
                    }
                ],
                "resourceName": "applicationservices"
            }
        }
    },
    "metadata": {
        "api_version": "3.2",
        "author": "",
        "comments": "",
        "date": "05-15-2015",
        "dev_backend": "",
        "dev_frontend": "",
        "dev_qd": "",
        "plm": "",
        "prd_url": "http://",
        "revisions": []
    },
    "model": {
        "RESTName": "applicationservice",
        "attributes": {
            "DSCP": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": "*",
                "description": "DSCP match condition to be set in the rule. It is either * or from 0-63",
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": false,
                "readonly": false,
                "required": true,
                "type": "string",
                "uniqueItems": false
            },
            "description": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "Description of the application service.",
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readonly": false,
                "required": true,
                "type": "string",
                "uniqueItems": false
            },
            "destinationPort": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": "*",
                "description": "The destination port to be matched if protocol is UDP or TCP. Value should be either * or single port number or a port range.",
                "filterable": false,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readonly": false,
                "required": true,
                "type": "string",
                "uniqueItems": false
            },
            "direction": {
                "allowedChars": null,
                "allowedChoices": [
                    "REFLEXIVE",
                    "UNIDIRECTIONAL"
                ],
                "autogenerated": false,
                "availability": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": "REFLEXIVE",
                "description": "Direction of the service. Default is UNIDIRECTIONAL. Possible values are UNIDIRECTIONAL, REFLEXIVE, .",
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readonly": false,
                "required": true,
                "type": "enum",
                "uniqueItems": false
            },
            "etherType": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": "0x0800",
                "description": "Ether type of the packet to be matched. Ether type can be * or a valid hexadecimal value",
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readonly": false,
                "required": true,
                "type": "string",
                "uniqueItems": false
            },
            "name": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "creationOnly": false,
                "defaultOrder": true,
                "defaultValue": null,
                "description": "Name of the application service.",
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readonly": false,
                "required": true,
                "type": "string",
                "uniqueItems": true
            },
            "protocol": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": "4",
                "description": "Protocol that must be matched.",
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readonly": false,
                "required": true,
                "type": "string",
                "uniqueItems": false
            },
            "sourcePort": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": "*",
                "description": "Source port to be matched if protocol is UDP or TCP. Value can be either * or single port number or a port range.",
                "filterable": false,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readonly": false,
                "required": true,
                "type": "string",
                "uniqueItems": false
            }
        },
        "description": "Represents a networking communication service.",
        "entityName": "ApplicationService",
        "package": "/appd",
        "resourceName": "applicationservices"
    }
}
