{
  "apis": {
    "children": {
      "/autodiscoveredgateways/id/metadatas": {
        "RESTName": "metadata",
        "entityName": "Metadata",
        "operations": [
          {
            "availability": null,
            "method": "GET"
          },
          {
            "availability": null,
            "method": "POST"
          }
        ],
        "resourceName": "metadatas"
      },
      "/autodiscoveredgateways/{id}/eventlogs": {
        "RESTName": "eventlog",
        "entityName": "EventLog",
        "operations": [
          {
            "availability": null,
            "method": "GET"
          }
        ],
        "resourceName": "eventlogs"
      },
      "/autodiscoveredgateways/{id}/nsports": {
        "RESTName": "nsport",
        "entityName": "NSPort",
        "operations": [
          {
            "availability": null,
            "method": "GET"
          }
        ],
        "resourceName": "nsports"
      },
      "/autodiscoveredgateways/{id}/ports": {
        "RESTName": "port",
        "entityName": "Port",
        "operations": [
          {
            "availability": null,
            "method": "GET"
          }
        ],
        "resourceName": "ports"
      },
      "/autodiscoveredgateways/{id}/services": {
        "RESTName": "service",
        "entityName": "WANService",
        "operations": [
          {
            "availability": null,
            "method": "GET"
          }
        ],
        "resourceName": "services"
      }
    },
    "parents": {
      "/autodiscoveredgateways": {
        "RESTName": "autodiscoveredgateway",
        "operations": [
          {
            "availability": null,
            "method": "GET"
          }
        ],
        "resourceName": "autodiscoveredgateways"
      }
    },
    "self": {
      "/autodiscoveredgateways/{id}": {
        "RESTName": "autodiscoveredgateway",
        "operations": [
          {
            "availability": null,
            "method": "GET"
          }
        ],
        "resourceName": "autodiscoveredgateways"
      }
    }
  },
  "model": {
    "RESTName": "autodiscoveredgateway",
    "attributes": {
      "controllers": {
        "allowedChars": null,
        "allowedChoices": null,
        "autogenerated": false,
        "availability": null,
        "channel": null,
        "creationOnly": false,
        "defaultOrder": false,
        "defaultValue": null,
        "description": "Controllers to which this gateway instance is associated with.",
        "exposed": true,
        "filterable": false,
        "format": null,
        "maxLength": null,
        "maxValue": null,
        "minLength": null,
        "minValue": null,
        "orderable": false,
        "readOnly": false,
        "required": false,
        "transient": false,
        "type": "Array[String]",
        "unique": false
      },
      "description": {
        "allowedChars": null,
        "allowedChoices": null,
        "autogenerated": false,
        "availability": null,
        "channel": null,
        "creationOnly": false,
        "defaultOrder": false,
        "defaultValue": null,
        "description": "A description of the Gateway",
        "exposed": true,
        "filterable": false,
        "format": null,
        "maxLength": null,
        "maxValue": null,
        "minLength": null,
        "minValue": null,
        "orderable": false,
        "readOnly": false,
        "required": false,
        "transient": false,
        "type": "string",
        "unique": false
      },
      "entityScope": {
        "allowedChars": null,
        "allowedChoices": null,
        "autogenerated": false,
        "availability": null,
        "channel": null,
        "creationOnly": false,
        "defaultOrder": false,
        "defaultValue": null,
        "description": "Specify if scope of entity is Data center or Enterprise level",
        "exposed": true,
        "filterable": false,
        "format": null,
        "maxLength": null,
        "maxValue": null,
        "minLength": null,
        "minValue": null,
        "orderable": false,
        "readOnly": false,
        "required": false,
        "transient": false,
        "type": "EntityScope",
        "unique": false
      },
      "gatewayID": {
        "allowedChars": null,
        "allowedChoices": null,
        "autogenerated": false,
        "availability": null,
        "channel": null,
        "creationOnly": false,
        "defaultOrder": false,
        "defaultValue": null,
        "description": "The Gateway associated with this  Auto Discovered Gateway  . This is a read only attribute",
        "exposed": true,
        "filterable": false,
        "format": null,
        "maxLength": null,
        "maxValue": null,
        "minLength": null,
        "minValue": null,
        "orderable": false,
        "readOnly": false,
        "required": false,
        "transient": false,
        "type": "string",
        "unique": false
      },
      "name": {
        "allowedChars": null,
        "allowedChoices": null,
        "autogenerated": false,
        "availability": null,
        "channel": null,
        "creationOnly": false,
        "defaultOrder": false,
        "defaultValue": null,
        "description": "Name of the Gateway",
        "exposed": true,
        "filterable": false,
        "format": null,
        "maxLength": null,
        "maxValue": null,
        "minLength": null,
        "minValue": null,
        "orderable": false,
        "readOnly": false,
        "required": true,
        "transient": false,
        "type": "string",
        "unique": false
      },
      "personality": {
        "allowedChars": null,
        "allowedChoices": [
          "DC7X50",
          "OTHER",
          "VRSG",
          "VSG",
          "VSA",
          "HARDWARE_VTEP",
          "NSG"
        ],
        "autogenerated": false,
        "availability": null,
        "channel": null,
        "creationOnly": false,
        "defaultOrder": false,
        "defaultValue": null,
        "description": "Personality of the Gateway - VSG,VRSG,NONE,OTHER, cannot be changed after creation. Possible values are VSG, VSA, VRSG, DC7X50, NSG, HARDWARE_VTEP, OTHER, .",
        "exposed": true,
        "filterable": false,
        "format": null,
        "maxLength": null,
        "maxValue": null,
        "minLength": null,
        "minValue": null,
        "orderable": false,
        "readOnly": false,
        "required": true,
        "transient": false,
        "type": "enum",
        "unique": false
      },
      "systemID": {
        "allowedChars": null,
        "allowedChoices": null,
        "autogenerated": false,
        "availability": null,
        "channel": null,
        "creationOnly": false,
        "defaultOrder": false,
        "defaultValue": null,
        "description": "Identifier of the Gateway",
        "exposed": true,
        "filterable": false,
        "format": null,
        "maxLength": null,
        "maxValue": null,
        "minLength": null,
        "minValue": null,
        "orderable": false,
        "readOnly": false,
        "required": false,
        "transient": false,
        "type": "string",
        "unique": false
      }
    },
    "description": "Represents Auto discovered Gateway",
    "entityName": "AutoDiscoveredGateway",
    "package": "/gateway",
    "resourceName": "autodiscoveredgateways"
  }
}