{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": false,
            "channel": null,
            "creation_only": false,
            "default_order": false,
            "default_value": null,
            "deprecated": false,
            "description": "The average bandwidth of the test in Mb/s",
            "exposed": true,
            "filterable": false,
            "format": null,
            "max_length": null,
            "max_value": 1000000,
            "min_length": null,
            "min_value": 0,
            "name": "bandwidth",
            "orderable": false,
            "read_only": false,
            "required": false,
            "subtype": null,
            "transient": false,
            "type": "float",
            "unique": false,
            "uniqueScope": null,
            "userlabel": "Bandwidth Mb/s"
        }
    ],
    "children": [],
    "model": {
        "allowed_job_commands": null,
        "create": false,
        "delete": false,
        "description": "Bandwidth Test Result",
        "entity_name": "BandwidthTestResult",
        "extends": [],
        "get": true,
        "package": "underlaytest",
        "resource_name": null,
        "rest_name": null,
        "root": null,
        "template": null,
        "update": true,
        "userlabel": "Bandwidth Test Result"
    }
}