{
    "resource_name": "cms", 
    "description": "Object that identifies a cloud management system", 
    "entity_name": "CloudMgmtSystem", 
    "package": "/cms", 
    "rest_name": "cms", 
    "extends": [
        "@base", 
        "@metadata"
    ], 
    "attributes": {
        "name": {
            "exposed": true, 
            "autogenerated": false, 
            "allowed_choices": null, 
            "availability": null, 
            "default_value": null, 
            "default_order": false, 
            "filterable": false, 
            "creation_only": false, 
            "max_length": null, 
            "orderable": false, 
            "type": "string", 
            "channel": null, 
            "read_only": false, 
            "allowed_chars": null, 
            "description": "Name of the cloud management system", 
            "format": null, 
            "max_value": null, 
            "min_value": null, 
            "transient": false, 
            "unique": false, 
            "min_length": null, 
            "required": false
        }
    }, 
    "get": true, 
    "children": {}, 
    "delete": true
}