{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": [
                "DESTINATION",
                "SOURCE"
            ],
            "autogenerated": false,
            "channel": null,
            "creation_only": false,
            "default_order": false,
            "default_value": "SOURCE",
            "deprecated": false,
            "description": "Indicates if this endpoint is the source/destination of a network connection.",
            "exposed": true,
            "filterable": true,
            "format": null,
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "name": "endPointType",
            "orderable": true,
            "read_only": false,
            "required": false,
            "subtype": null,
            "transient": false,
            "type": "enum",
            "unique": false,
            "uniqueScope": null
        }
    ],
    "children": [],
    "model": {
        "create": null,
        "delete": true,
        "description": null,
        "entity_name": "Connectionendpoint",
        "extends": [],
        "get": true,
        "package": null,
        "resource_name": "connectionendpoints",
        "rest_name": "connectionendpoint",
        "root": null,
        "update": true
    }
}