{
    "apis": {
        "children": {}, 
        "parents": {
            "/dscpforwardingclasstables/{id}/dscpforwardingclassmappings": {
                "RESTName": "dscpforwardingclasstable", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }, 
                    {
                        "availability": null, 
                        "method": "POST"
                    }
                ], 
                "resourceName": "dscpforwardingclasstables"
            }
        }, 
        "self": {
            "/dscpforwardingclassmappings/{id}": {
                "RESTName": "dscpforwardingclassmapping", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "PUT"
                    }, 
                    {
                        "availability": null, 
                        "method": "DELETE"
                    }, 
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "dscpforwardingclassmappings"
            }
        }
    }, 
    "metadata": {
        "api_version": "3.2", 
        "author": "", 
        "comments": "", 
        "date": "05-18-2015", 
        "dev_backend": "", 
        "dev_frontend": "", 
        "dev_qd": "", 
        "plm": "", 
        "prd_url": "http://", 
        "revisions": []
    }, 
    "model": {
        "RESTName": "dscpforwardingclassmapping", 
        "attributes": {
            "DSCP": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "DSCP value range from enumeration of 65 values: *, 0, 1 ... 63", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "string", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "forwardingClass": {
                "allowedChars": null, 
                "allowedChoices": [
                    "D", 
                    "E", 
                    "F", 
                    "G", 
                    "A", 
                    "B", 
                    "C", 
                    "H", 
                    "NONE"
                ], 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "Class of service to be used. Service classes in order of priority are A, B, C, D, E, F, G and H Possible values are NONE, A, B, C, D, E, F, G, H, .", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "enum", 
                "unique": false, 
                "uniqueItems": false
            }
        }, 
        "description": "Provides the definition of a single DSCP -> Forwarding class mapping that is part of a Table used in QoS policies.", 
        "entityName": "DSCPForwardingClassMapping", 
        "package": "/policy", 
        "resourceName": "dscpforwardingclassmappings"
    }
}