{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": false,
            "channel": null,
            "creation_only": false,
            "default_order": false,
            "default_value": null,
            "deprecated": false,
            "description": "Name of the Gateway",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "max_length": 255,
            "max_value": null,
            "min_length": 0,
            "min_value": null,
            "name": "gatewayName",
            "orderable": true,
            "read_only": false,
            "required": false,
            "subtype": null,
            "transient": false,
            "type": "string",
            "unique": false,
            "uniqueScope": null,
            "userlabel": "Gateway Name"
        }
    ],
    "children": [],
    "model": {
        "allowed_job_commands": null,
        "create": false,
        "delete": false,
        "description": "Represents the vport status info at individual gateway for ethernet segment group",
        "entity_name": "ESGroupVPortInfo",
        "extends": [],
        "get": false,
        "package": null,
        "resource_name": null,
        "rest_name": null,
        "root": null,
        "template": null,
        "update": false,
        "userlabel": "VPort Info"
    }
}