{
    "apis": {
        "children": {}, 
        "parents": {
            "/enterprises/{id}/ikev2encryptionprofiles": {
                "RESTName": "enterprise", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }, 
                    {
                        "availability": null, 
                        "method": "POST"
                    }
                ], 
                "resourceName": "enterprises"
            }
        }, 
        "self": {
            "/ikev2encryptionprofiles/{id}": {
                "RESTName": "ikev2encryptionprofile", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "PUT"
                    }, 
                    {
                        "availability": null, 
                        "method": "DELETE"
                    }, 
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "ikev2encryptionprofiles"
            }
        }
    }, 
    "metadata": {
        "api_version": "3.2", 
        "author": "", 
        "comments": "", 
        "date": "05-18-2015", 
        "dev_backend": "", 
        "dev_frontend": "", 
        "dev_qd": "", 
        "plm": "", 
        "prd_url": "http://", 
        "revisions": []
    }, 
    "model": {
        "RESTName": "ikev2encryptionprofile", 
        "attributes": {
            "authenticationMethod": {
                "allowedChars": null, 
                "allowedChoices": [
                    "PRE_SHARED_KEY", 
                    "RSA_SIGNATURE", 
                    "RSA_NONCE"
                ], 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "IKEv2 Authentication Method. Possible values are RSA_SIGNATURE, RSA_NONCE, PRE_SHARED_KEY, .", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "enum", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "description": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "A description of the Profile instance created.", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "string", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "diffieHelmanGroupIdentifier": {
                "allowedChars": null, 
                "allowedChoices": [
                    "GROUP_5_1024_BIT_DH", 
                    "GROUP_15_3072_BIT_DH", 
                    "GROUP_2_1024_BIT_DH", 
                    "GROUP_16_4096_BIT_DH", 
                    "GROUP_1_768_BIT_DH", 
                    "GROUP_24_2048_BIT_ECDH", 
                    "GROUP_20_384_BIT_ECDH", 
                    "GROUP_19_256_BIT_ECDH", 
                    "GROUP_14_2048_BIT_DH"
                ], 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "IKEv2 Diffie-Helman Group Identifier. Possible values are GROUP_1_768_BIT_DH, GROUP_2_1024_BIT_DH, GROUP_5_1024_BIT_DH, GROUP_14_2048_BIT_DH, GROUP_15_3072_BIT_DH, GROUP_16_4096_BIT_DH, GROUP_19_256_BIT_ECDH, GROUP_20_384_BIT_ECDH, GROUP_24_2048_BIT_ECDH, .", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "enum", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "encryptionAlgorithm": {
                "allowedChars": null, 
                "allowedChoices": [
                    "AES192", 
                    "TDES", 
                    "DES", 
                    "AES256", 
                    "AES128"
                ], 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "IKEv2 Encryption Algorithm. Possible values are DES, TDES, AES128, AES192, AES256, .", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "enum", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "encryptionKeyLifetime": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "IKEv2 Encryption Key Lifetime in Seconds. Min=60, Max=86400", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "integer", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "hashAlgorithm": {
                "allowedChars": null, 
                "allowedChoices": [
                    "SHA256", 
                    "SHA1", 
                    "MD5"
                ], 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "IKEv2 Hash Algorithm. Possible values are MD5, SHA1, SHA256, .", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "enum", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "name": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "Name of the Encryption Profile", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": true, 
                "type": "string", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "securityAssociationLifetime": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "IKE Security Association Lifetime in Seconds. Min=60, Max=86400", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "integer", 
                "unique": false, 
                "uniqueItems": false
            }
        }, 
        "description": "Represents an IKEv2 Profile", 
        "entityName": "IKEv2EncryptionProfile", 
        "package": "/keyserver", 
        "resourceName": "ikev2encryptionprofiles"
    }
}