{
    "attributes": {
        "upgradeAction": {
            "description": "Upgrade action for NSG associated with this Infrastructure Gateway Profile instance.  By default, there is no upgrade. Possible values are DOWNLOAD_ONLY, DOWNLOAD_AND_UPGRADE_AT_WINDOW, DOWNLOAD_AND_UPGRADE_NOW, UPGRADE_NOW, UPGRADE_AT_BOOTSTRAPPING, NONE, .", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "allowed_choices": [
                "UPGRADE_AT_BOOTSTRAPPING", 
                "DOWNLOAD_AND_UPGRADE_NOW", 
                "UPGRADE_NOW", 
                "NONE", 
                "DOWNLOAD_AND_UPGRADE_AT_WINDOW", 
                "DOWNLOAD_ONLY"
            ], 
            "orderable": true, 
            "type": "enum"
        }, 
        "remoteLogMode": {
            "description": "Type of Log Server for system logs generated by Gateways associated with this Infrastructure Profile.  Valid values are SCP, SFTP, RSyslog, and Disabled.  This field is set to Disabled by default. Possible values are SCP, SFTP, RSYSLOG, DISABLED, .", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "allowed_choices": [
                "SCP", 
                "RSYSLOG", 
                "SFTP", 
                "DISABLED"
            ], 
            "orderable": true, 
            "type": "enum"
        }, 
        "remoteLogServerAddress": {
            "description": "Primary Log Server for system logs generated by Gateways associated with this Infrastructure Profile.  Can be an IP address or a URL.  This field is optional.", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "remoteLogDirPath": {
            "description": "Path on the remote log server where the logs generated by the NSG are to be stored.  This field is only useful for SCP and SFTP.", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "NTPServerKeyID": {
            "description": "Correspond to the key ID on the NTP server that matches the ntpServerKey value.  Valid values are from 1 to 255 as specified by SR-OS and 0 to specify unused (VSD/NSG only).", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "integer"
        }, 
        "activeController": {
            "description": "VSC Active Controller :  IP Address of the primary VSC system NSG instances associated to this profile will be reaching for.", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "statsCollectorPort": {
            "description": "The port to open by the proxy for stats collector to use", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "integer"
        }, 
        "systemSyncScheduler": {
            "description": "Time in a Cron format when configuration update are being applied on the Gateway (NSG).  This property is linked to systemSyncWindow.  Default value is every midnight (0 0 * * *).  Format:  Minutes Hours DayOfMonth Month DayOfWeek", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "enterpriseID": {
            "description": "Enterprise/Organisation associated with this Profile instance.", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "metadataUpgradePath": {
            "description": "Path/URL to retrieve the NSG Upgrade information meta data files.  From that meta data, the NSG will be able to retrieve the upgrade package files and perform some validations.  It is expected that the meta data file is in JSON format.  RFC 2616 states that there are no 'official' maximum length for a URL but different browsers and servers have limits.  Our friendly Internet Explorer has a maximum of 'around' 2048 characters, we shall use this as a limit here.", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "remoteLogUsername": {
            "description": "Username to be used when accessing the remote log server via SCP or SFTP.  This field is only useful for SCP and SFTP.", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "datapathSyncTimeout": {
            "description": "Datapath flows sync-time-interval specified in milliseconds (default: 1000)", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "float"
        }, 
        "standbyController": {
            "description": "VSC Standby Controller :  IP Address of the standby VSC system NSG instances associated to this profile will be reaching for.", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "description": {
            "description": "A description of the Profile instance created.", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "flowEvictionThreshold": {
            "description": "Number of flows at which eviction from kernel flow table will be triggered (default: 2500)", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "float"
        }, 
        "probeInterval": {
            "description": "Openflow echo timer in millisecond", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "float"
        }, 
        "deadTimer": {
            "description": "Time, in seconds, allowed for a Gateway to be inactive before the VSD revokes its certificates and marks it as untrusted.  Default value is 1 hour (3600) Possible values are NONE, TEN_MINUTES, THIRTY_MINUTES, ONE_HOUR, TWO_HOURS, THREE_HOURS, FOUR_HOURS, FIVE_HOURS, SIX_HOURS, MAXIMUM_DURATION, .", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "allowed_choices": [
                "THREE_HOURS", 
                "THIRTY_MINUTES", 
                "TEN_MINUTES", 
                "ONE_HOUR", 
                "FOUR_HOURS", 
                "SIX_HOURS", 
                "MAXIMUM_DURATION", 
                "TWO_HOURS", 
                "FIVE_HOURS", 
                "NONE"
            ], 
            "orderable": true, 
            "type": "enum"
        }, 
        "systemSyncWindow": {
            "description": "Length of time, in seconds, given to a Gateway to apply a configuration change.  This property is closely linked to systemSyncScheduler.  Default value is 1 hour (3600 s) Possible values are NONE, TEN_MINUTES, THIRTY_MINUTES, ONE_HOUR, TWO_HOURS, THREE_HOURS, FOUR_HOURS, FIVE_HOURS, SIX_HOURS, MAXIMUM_DURATION, .", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "allowed_choices": [
                "THREE_HOURS", 
                "THIRTY_MINUTES", 
                "TEN_MINUTES", 
                "ONE_HOUR", 
                "FOUR_HOURS", 
                "SIX_HOURS", 
                "MAXIMUM_DURATION", 
                "TWO_HOURS", 
                "FIVE_HOURS", 
                "NONE"
            ], 
            "orderable": true, 
            "type": "enum"
        }, 
        "NTPServerKey": {
            "description": "If set, this represents the security key for the Gateway to communicate with the NTP server (a VSC).", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "name": {
            "description": "Name of the Infrastructure Profile", 
            "format": "free", 
            "filterable": true, 
            "uniqueScope": "no", 
            "required": true, 
            "exposed": true, 
            "orderable": true, 
            "type": "string"
        }, 
        "proxyDNSName": {
            "description": "Proxy DNS Name :  DNS Name of the system acting as a proxy between the NSG instances and the VSD.", 
            "format": "free", 
            "filterable": true, 
            "uniqueScope": "no", 
            "required": true, 
            "exposed": true, 
            "orderable": true, 
            "type": "string"
        }, 
        "remoteLogServerPort": {
            "description": "Port to be used to access the Remote Syslog server.  By default, this is port 514.", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "integer"
        }, 
        "remoteLogPassword": {
            "description": "Password to be used when accessing the remote log server via SCP or SFTP.  This field is only useful for SCP and SFTP.", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "useTwoFactor": {
            "description": "Use Two Factor :  When set to true, the use of two independent authentication factors will be used to secure the installed NSG.  When set to false, there is an assumption that the NSG is being installed in a secure environment and the installer is also trusted.  The defaut value is true, using 2-factor.", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "boolean"
        }, 
        "enterprise": {
            "description": "Name of the enterprise/organisation associated with this Profile instance.  This is a read only attribute", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }
    }, 
    "model": {
        "resource_name": "infrastructuregatewayprofiles", 
        "description": "Represents Infrastructure Gateway Profile", 
        "entity_name": "InfrastructureGatewayProfile", 
        "package": "infrastructure", 
        "get": true, 
        "update": true, 
        "rest_name": "infrastructuregatewayprofile", 
        "extends": [
            "@base", 
            "@metadata"
        ], 
        "delete": true
    }
}