{
    "apis": {
        "children": {
            "/keyservermonitorseks/{id}/keyservermonitorencryptedseeds": {
                "RESTName": "keyservermonitorencryptedseed", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "keyservermonitorencryptedseeds"
            }, 
            "/keyservermonitorseks/{id}/keyservermonitorencryptedseks": {
                "RESTName": "keyservermonitorencryptedsek", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "keyservermonitorencryptedseks"
            }
        }, 
        "parents": {
            "/keyservermonitors/{id}/keyservermonitorseks": {
                "RESTName": "keyservermonitor", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }, 
                    {
                        "availability": null, 
                        "method": "POST"
                    }
                ], 
                "resourceName": "keyservermonitors"
            }
        }, 
        "self": {
            "/keyservermonitorseks/{id}": {
                "RESTName": "keyservermonitorsek", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "PUT"
                    }, 
                    {
                        "availability": null, 
                        "method": "DELETE"
                    }, 
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "keyservermonitorseks"
            }
        }
    }, 
    "metadata": {
        "api_version": "3.2", 
        "author": "", 
        "comments": "", 
        "date": "05-15-2015", 
        "dev_backend": "", 
        "dev_frontend": "", 
        "dev_qd": "", 
        "plm": "", 
        "prd_url": "http://", 
        "revisions": []
    }, 
    "model": {
        "RESTName": "keyservermonitorsek", 
        "attributes": {
            "creationTime": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "The time this entry was created (milliseconds since epoch)", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readonly": false, 
                "required": false, 
                "type": "long", 
                "uniqueItems": false
            }, 
            "lifetime": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "The lifetime of this entry (seconds)", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readonly": false, 
                "required": false, 
                "type": "integer", 
                "uniqueItems": false
            }, 
            "seedPayloadAuthenticationAlgorithm": {
                "allowedChars": null, 
                "allowedChoices": [
                    "HMAC_SHA512", 
                    "HMAC_SHA1", 
                    "HMAC_SHA256"
                ], 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "SEK Payload Signature Algorithm Possible values are HMAC_SHA1, HMAC_SHA256, HMAC_SHA512, .", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readonly": false, 
                "required": false, 
                "type": "enum", 
                "uniqueItems": false
            }, 
            "seedPayloadEncryptionAlgorithm": {
                "allowedChars": null, 
                "allowedChoices": [
                    "AES_128_CBC", 
                    "AES_256_CBC", 
                    "TRIPLE_DES_CBC"
                ], 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "SEK Payload Encryption Algorithm Possible values are AES_128_CBC, AES_256_CBC, TRIPLE_DES_CBC, .", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readonly": false, 
                "required": false, 
                "type": "enum", 
                "uniqueItems": false
            }, 
            "startTime": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "The time this entry  was activated (milliseconds since epoch)", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readonly": false, 
                "required": false, 
                "type": "long", 
                "uniqueItems": false
            }
        }, 
        "description": "Represents a Keyserver Monitor SEK Snapshot", 
        "entityName": "KeyServerMonitorSEK", 
        "package": "/keyserver", 
        "resourceName": "keyservermonitorseks"
    }
}