{
    "resource_name": "multinicvports", 
    "description": "Encapsulates the Multi NIC VPort information for system monitor entity.", 
    "entity_name": "MultiNICVPort", 
    "package": "/sysmon", 
    "rest_name": "multinicvport", 
    "extends": [
        "@base", 
        "@metadata"
    ], 
    "attributes": {
        "name": {
            "exposed": true, 
            "autogenerated": false, 
            "allowed_choices": null, 
            "availability": null, 
            "default_value": null, 
            "default_order": false, 
            "filterable": false, 
            "creation_only": false, 
            "max_length": null, 
            "orderable": false, 
            "type": "string", 
            "channel": null, 
            "read_only": false, 
            "allowed_chars": null, 
            "description": "Name for the Multi NIC VPort.", 
            "format": null, 
            "max_value": null, 
            "min_value": null, 
            "transient": false, 
            "unique": false, 
            "min_length": null, 
            "required": false
        }
    }, 
    "get": true, 
    "children": {
        "vport": {
            "relationship": "child", 
            "get": true
        }
    }
}