{
    "apis": {
        "children": {
            "/multicastlists/{id}/multicastchannelmaps": {
                "RESTName": "multicastchannelmap", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }, 
                    {
                        "availability": null, 
                        "method": "PUT"
                    }
                ], 
                "resourceName": "multicastchannelmaps"
            }
        }, 
        "parents": {
            "/enterpriseprofiles/{id}/multicastlists": {
                "RESTName": "enterpriseprofile", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "enterpriseprofiles"
            }, 
            "/enterprises/{id}/multicastlists": {
                "RESTName": "enterprise", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "enterprises"
            }
        }, 
        "self": {
            "/multicastlists/{id}": {
                "RESTName": "multicastlist", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "multicastlists"
            }
        }
    }, 
    "metadata": {
        "api_version": "3.2", 
        "author": "", 
        "comments": "", 
        "date": "05-19-2015", 
        "dev_backend": "", 
        "dev_frontend": "", 
        "dev_qd": "", 
        "plm": "", 
        "prd_url": "http://", 
        "revisions": []
    }, 
    "model": {
        "RESTName": "multicastlist", 
        "attributes": {
            "mcastType": {
                "allowedChars": null, 
                "allowedChoices": [
                    "SEND", 
                    "RECEIVE"
                ], 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "Type of multicast list - send or receive Possible values are SEND, RECEIVE, .", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "enum", 
                "unique": false, 
                "uniqueItems": false
            }
        }, 
        "description": "This is the definition of a MultiCast Channel List", 
        "entityName": "MultiCastList", 
        "package": "/network", 
        "resourceName": "multicastlists"
    }
}