{
    "apis": {
        "children": {
            "/policydecisions/{id}/qos": {
                "RESTName": "qos", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "qos"
            }
        }, 
        "parents": {
            "/bridgeinterfaces/{id}/policydecisions": {
                "RESTName": "bridgeinterface", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "bridgeinterfaces"
            }, 
            "/hostinterfaces/{id}/policydecisions": {
                "RESTName": "hostinterface", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "hostinterfaces"
            }, 
            "/vminterfaces/{id}/policydecisions": {
                "RESTName": "vminterface", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "vminterfaces"
            }
        }, 
        "self": {
            "/policydecisions/{id}": {
                "RESTName": "policydecision", 
                "operations": [
                    {
                        "availability": null, 
                        "method": "GET"
                    }
                ], 
                "resourceName": "policydecisions"
            }
        }
    }, 
    "metadata": {
        "api_version": "3.2", 
        "author": "", 
        "comments": "", 
        "date": "05-19-2015", 
        "dev_backend": "", 
        "dev_frontend": "", 
        "dev_qd": "", 
        "plm": "", 
        "prd_url": "http://", 
        "revisions": []
    }, 
    "model": {
        "RESTName": "policydecision", 
        "attributes": {
            "egressACLs": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "List of actual Egress ACLs that will be applied on the interface of this VM", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "array", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "egressQos": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "Egress QoS primitive that was selected", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "EgressQosPrimitive", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "fipACLs": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "List of actual Egress ACLs that will be applied on the interface of this VM", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "array", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "ingressACLs": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "List of actual Ingress ACLs that will be applied on the interface of this VM", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "array", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "ingressAdvFwd": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "List of actual Ingress Redirect ACLs that will be applied on the interface of this VM", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "array", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "ingressExternalServiceACLs": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "List of actual Ingress External Service ACLs that will be applied on the interface of this VM", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "array", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "qos": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "QoS primitive that was selected based on inheritance policies", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "QosPrimitive", 
                "unique": false, 
                "uniqueItems": false
            }, 
            "stats": {
                "allowedChars": null, 
                "allowedChoices": null, 
                "autogenerated": false, 
                "availability": null, 
                "creationOnly": false, 
                "defaultOrder": false, 
                "defaultValue": null, 
                "description": "Stats primitive that was selected based on inheritance policies", 
                "filterable": false, 
                "format": null, 
                "maxLength": null, 
                "maxValue": null, 
                "minLength": null, 
                "minValue": null, 
                "orderable": false, 
                "readOnly": false, 
                "required": false, 
                "type": "StatisticsPolicy", 
                "unique": false, 
                "uniqueItems": false
            }
        }, 
        "description": "This object is a read only object that provides the policy decisions for a particular VM interface", 
        "entityName": "PolicyDecision", 
        "package": "/policy", 
        "resourceName": "policydecisions"
    }
}