{
<<<<<<< HEAD
    "attributes": {
        "IPType": {
            "allowed_choices": [
                "IPV6",
                "IPV4",
                "DUALSTACK"
            ],
            "description": "IPv4 or IPv6(only IPv4 is supported in R1.0) Possible values are IPV4, IPV6, .",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "orderable": true,
            "type": "enum",
            "uniqueScope": "no"
        },
        "address": {
            "description": "IP address of the subnet defined. In case of zone, this is an optional field for and allows users to allocate an IP address range to a zone. The VSD will auto-assign IP addresses to subnets from this range if a specific IP address is not defined for the subnet",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "orderable": true,
            "required": true,
            "type": "string",
            "uniqueScope": "no"
        },
        "name": {
            "description": "Name of the current entity(Zone or zone template or subnet etc..) Valid characters are alphabets, numbers, space and hyphen( - ).",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "orderable": true,
            "required": true,
            "type": "string",
            "uniqueScope": "no"
        },
        "netmask": {
            "description": "Netmask of the subnet defined",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "orderable": true,
            "required": true,
            "type": "string",
            "uniqueScope": "no"
        },
        "IPv6Address": {
            "description": "IPv6 address of the subnet defined. In case of zone, this is an optional field for and allows users to allocate an IP address range to a zone. The VSD will auto-assign IP addresses to subnets from this range if a specific IP address is not defined for the subnet",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "orderable": true,
            "required": false,
            "type": "string",
            "uniqueScope": "no"
        },
    },
    "children": {
        "eventlog": {
            "get": true,
            "relationship": "child"
        }
    },
    "model": {
        "delete": true,
        "description": "Similar to the enterprise macros, the public network macro allows an administrator of an enterprise to define range of subnets that can be used by users in the ACL definition",
        "entity_name": "PublicNetworkMacro",
=======
    "apis": {
        "children": {
            "/publicnetworks/{id}/eventlogs": {
                "RESTName": "eventlog",
                "entityName": "EventLog",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    }
                ],
                "resourceName": "eventlogs"
            }
        },
        "parents": {
            "/enterprises/{id}/publicnetworks": {
                "RESTName": "enterprise",
                "operations": [
                    {
                        "availability": null,
                        "method": "GET"
                    },
                    {
                        "availability": null,
                        "method": "POST"
                    }
                ],
                "resourceName": "enterprises"
            }
        },
        "self": {
            "/publicnetworks/{id}": {
                "RESTName": "publicnetwork",
                "operations": [
                    {
                        "availability": null,
                        "method": "PUT"
                    },
                    {
                        "availability": null,
                        "method": "DELETE"
                    },
                    {
                        "availability": null,
                        "method": "GET"
                    }
                ],
                "resourceName": "publicnetworks"
            }
        }
    },
    "model": {
        "RESTName": "publicnetwork",
        "attributes": {
            "IPType": {
                "allowedChars": null,
                "allowedChoices": [
                    "DUALSTACK",
                    "IPV4",
                    "IPV6"
                ],
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": "IPV4",
                "description": "IPv4 or IPv6(only IPv4 is supported in R1.0) Possible values are IPV4, IPV6, .",
                "exposed": true,
                "filterable": true,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": true,
                "readOnly": false,
                "required": true,
                "transient": false,
                "type": "enum",
                "unique": false
            },
            "address": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "IP address of the subnet defined. In case of zone, this is an optional field for and allows users to allocate an IP address range to a zone. The VSD will auto-assign IP addresses to subnets from this range if a specific IP address is not defined for the subnet",
                "exposed": true,
                "filterable": false,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": false,
                "readOnly": false,
                "required": true,
                "transient": false,
                "type": "string",
                "unique": false
            },
            "name": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "Name of the current entity(Zone or zone template or subnet etc..) Valid characters are alphabets, numbers, space and hyphen( - ).",
                "exposed": true,
                "filterable": false,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": false,
                "readOnly": false,
                "required": true,
                "transient": false,
                "type": "string",
                "unique": false
            },
            "netmask": {
                "allowedChars": null,
                "allowedChoices": null,
                "autogenerated": false,
                "availability": null,
                "channel": null,
                "creationOnly": false,
                "defaultOrder": false,
                "defaultValue": null,
                "description": "Netmask of the subnet defined",
                "exposed": true,
                "filterable": false,
                "format": null,
                "maxLength": null,
                "maxValue": null,
                "minLength": null,
                "minValue": null,
                "orderable": false,
                "readOnly": false,
                "required": true,
                "transient": false,
                "type": "string",
                "unique": false
            }
        },
        "description": "Similar to the enterprise macros, the public network macro allows an administrator of an enterprise to define range of subnets that can be used by users in the ACL definition",
        "entityName": "PublicNetworkMacro",
>>>>>>> edc8a1057eda55ded4ee32335293010fd5742f6f
        "extends": [
            "@base",
            "@metadata"
        ],
<<<<<<< HEAD
        "get": true,
        "package": "network",
        "resource_name": "publicnetworks",
        "rest_name": "publicnetwork",
        "update": true
=======
        "package": "/network",
        "resourceName": "publicnetworks"
>>>>>>> edc8a1057eda55ded4ee32335293010fd5742f6f
    }
}