{
    "attributes": {
        "redundancyEnabled": {
            "description": "Allow/Disallow redundant appliances and VIP", 
            "format": "free", 
            "filterable": true, 
            "uniqueScope": "no", 
            "required": true, 
            "exposed": true, 
            "orderable": true, 
            "type": "boolean"
        }, 
        "name": {
            "description": "Name of this redirection target", 
            "format": "free", 
            "filterable": true, 
            "uniqueScope": "no", 
            "required": true, 
            "exposed": true, 
            "orderable": true, 
            "type": "string"
        }, 
        "triggerType": {
            "required": true, 
            "description": "Trigger type, THIS IS READ ONLY. Possible values are NONE, GARP, .", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "allowed_choices": [
                "GARP", 
                "NONE"
            ], 
            "orderable": true, 
            "type": "enum"
        }, 
        "endPointType": {
            "required": true, 
            "description": "EndpointType defines the type of header rewrite and forwarding performed by VRS when the endpoint is used as a PBR destination. NONE type is deprecated. Possible values are NONE, L3, VIRTUAL_WIRE, .", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "allowed_choices": [
                "L3", 
                "VIRTUAL_WIRE", 
                "NONE"
            ], 
            "orderable": true, 
            "type": "enum"
        }, 
        "templateID": {
            "description": "Template to which this redirection target belongs to", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "virtualNetworkID": {
            "description": "Auto Generated by VSD. Each vPortTag with redundancy=enable and EndpointType != none will have a globally unique ESI & VNID generated by VSD", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "ESI": {
            "description": "ESI id, globally unique", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }, 
        "description": {
            "description": "Description of this redirection target", 
            "format": "free", 
            "filterable": true, 
            "exposed": true, 
            "uniqueScope": "no", 
            "orderable": true, 
            "type": "string"
        }
    }, 
    "model": {
        "resource_name": "redirectiontargets", 
        "description": "A group/collection of vports that belong to the same domain", 
        "entity_name": "RedirectionTarget", 
        "package": "vport", 
        "get": true, 
        "update": true, 
        "rest_name": "redirectiontarget", 
        "extends": [
            "@base", 
            "@metadata"
        ], 
        "delete": true
    }, 
    "children": {
        "job": {
            "create": true, 
            "relationship": "child"
        }, 
        "vport": {
            "update": true, 
            "relationship": "child", 
            "get": true
        }, 
        "eventlog": {
            "relationship": "child", 
            "get": true
        }, 
        "virtualip": {
            "create": true, 
            "relationship": "child", 
            "get": true
        }
    }
}