{
    "attributes": {
        "ESI": {
            "description": "ESI id, globally unique",
            "exposed": true,
            "format": "free",
            "type": "string",
            "uniqueScope": "no"
        },
        "description": {
            "description": "Description of this redirection target",
            "exposed": true,
            "format": "free",
            "type": "string",
            "uniqueScope": "no"
        },
        "endPointType": {
            "allowed_choices": [
                "L3",
                "NONE",
                "VIRTUAL_WIRE"
            ],
            "description": "EndpointType defines the type of header rewrite and forwarding performed by VRS when the endpoint is used as a PBR destination. NONE type is deprecated. Possible values are NONE, L3, VIRTUAL_WIRE, .",
            "exposed": true,
            "format": "free",
            "required": true,
            "type": "enum",
            "uniqueScope": "no"
        },
        "name": {
            "description": "Name of this redirection target",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "orderable": true,
            "required": true,
            "type": "string",
            "uniqueScope": "no"
        },
        "redundancyEnabled": {
            "description": "Allow/Disallow redundant appliances and VIP",
            "exposed": true,
            "format": "free",
            "required": true,
            "type": "boolean",
            "uniqueScope": "no"
        },
        "templateID": {
            "description": "Template to which this redirection target belongs to",
            "exposed": true,
            "format": "free",
            "type": "string",
            "uniqueScope": "no"
        },
        "triggerType": {
            "allowed_choices": [
                "GARP",
                "NONE"
            ],
            "description": "Trigger type, THIS IS READ ONLY. Possible values are NONE, GARP, .",
            "exposed": true,
            "format": "free",
            "required": true,
            "type": "enum",
            "uniqueScope": "no"
        },
        "virtualNetworkID": {
            "description": "Auto Generated by VSD. Each vPortTag with redundancy=enable and EndpointType != none will have a globally unique ESI & VNID generated by VSD",
            "exposed": true,
            "format": "free",
            "type": "string",
            "uniqueScope": "no"
        }
    },
    "children": {
        "eventlog": {
            "get": true,
            "relationship": "child"
        },
        "job": {
            "create": true,
            "relationship": "child"
        },
        "virtualip": {
            "create": true,
            "get": true,
            "relationship": "child"
        },
        "vport": {
            "get": true,
            "relationship": "child",
            "update": true
        }
    },
    "model": {
        "delete": true,
        "description": "A group/collection of vports that belong to the same domain.",
        "entity_name": "RedirectionTarget",
        "extends": [
            "@audited",
            "@base",
            "@metadata"
        ],
        "get": true,
        "package": "vport",
        "resource_name": "redirectiontargets",
        "rest_name": "redirectiontarget",
        "update": true
    }
}