{
  "apis": {
    "children": {},
    "parents": {
      "/domains/{id}/uplinkroutedistinguishers": {
        "RESTName": "domain",
        "operations": [
          {
            "availability": null,
            "method": "GET"
          }
        ],
        "resourceName": "domains"
      },
      "/l2domains/{id}/uplinkroutedistinguishers": {
        "RESTName": "l2domain",
        "operations": [
          {
            "availability": null,
            "method": "GET"
          }
        ],
        "resourceName": "l2domains"
      },
      "/uplinkroutedistinguishers": {
        "RESTName": "uplinkroutedistinguisher",
        "operations": [
          {
            "availability": null,
            "method": "GET"
          }
        ],
        "resourceName": "uplinkroutedistinguishers"
      }
    },
    "self": {
      "/uplinkroutedistinguishers/{id}": {
        "RESTName": "uplinkroutedistinguisher",
        "operations": [
          {
            "availability": null,
            "method": "GET"
          }
        ],
        "resourceName": "uplinkroutedistinguishers"
      }
    }
  },
  "model": {
    "RESTName": "uplinkroutedistinguisher",
    "attributes": {
      "entityScope": {
        "allowedChars": null,
        "allowedChoices": null,
        "autogenerated": false,
        "availability": null,
        "channel": null,
        "creationOnly": false,
        "defaultOrder": false,
        "defaultValue": null,
        "description": "Specify if scope of entity is Data center or Enterprise level",
        "exposed": true,
        "filterable": false,
        "format": null,
        "maxLength": null,
        "maxValue": null,
        "minLength": null,
        "minValue": null,
        "orderable": false,
        "readOnly": false,
        "required": false,
        "transient": false,
        "type": "EntityScope",
        "unique": false
      },
      "routeDistinguisher": {
        "allowedChars": null,
        "allowedChoices": null,
        "autogenerated": false,
        "availability": null,
        "channel": null,
        "creationOnly": false,
        "defaultOrder": false,
        "defaultValue": null,
        "description": "The uplink route distinguisher value is used to identify which route packets should be flowing through with regards to having multiple network ports on the VRS/NSG.",
        "exposed": true,
        "filterable": false,
        "format": null,
        "maxLength": null,
        "maxValue": null,
        "minLength": null,
        "minValue": null,
        "orderable": false,
        "readOnly": false,
        "required": false,
        "transient": false,
        "type": "string",
        "unique": false
      },
      "uplinkType": {
        "allowedChars": null,
        "allowedChoices": [
          "RD_PRIMARY2",
          "RD_PRIMARY1",
          "RD_SECONDARY1",
          "RD_SECONDARY2"
        ],
        "autogenerated": false,
        "availability": null,
        "channel": null,
        "creationOnly": false,
        "defaultOrder": false,
        "defaultValue": null,
        "description": "Indicates the uplink type associated with the instance of Uplink Route Distinguisher.  Default value is RD Primary1 Possible values are RD_PRIMARY1, RD_PRIMARY2, RD_SECONDARY1, RD_SECONDARY2, .",
        "exposed": true,
        "filterable": false,
        "format": null,
        "maxLength": null,
        "maxValue": null,
        "minLength": null,
        "minValue": null,
        "orderable": false,
        "readOnly": false,
        "required": false,
        "transient": false,
        "type": "enum",
        "unique": false
      }
    },
    "description": "Represents a network port uplink Route Distinguisher value.",
    "entityName": "UplinkRD",
    "package": "/network",
    "resourceName": "uplinkroutedistinguishers"
  }
}