{
    "resource_name": "uplinkroutedistinguishers", 
    "description": "Represents a network port uplink Route Distinguisher value.", 
    "entity_name": "UplinkRD", 
    "package": "/network", 
    "rest_name": "uplinkroutedistinguisher", 
    "extends": [
        "@base", 
        "@metadata"
    ], 
    "attributes": {
        "routeDistinguisher": {
            "exposed": true, 
            "autogenerated": false, 
            "allowed_choices": null, 
            "availability": null, 
            "default_value": null, 
            "default_order": false, 
            "filterable": false, 
            "creation_only": false, 
            "max_length": null, 
            "orderable": false, 
            "type": "string", 
            "channel": null, 
            "read_only": false, 
            "allowed_chars": null, 
            "description": "The uplink route distinguisher value is used to identify which route packets should be flowing through with regards to having multiple network ports on the VRS/NSG.", 
            "format": null, 
            "max_value": null, 
            "min_value": null, 
            "transient": false, 
            "unique": false, 
            "min_length": null, 
            "required": false
        }, 
        "uplinkType": {
            "exposed": true, 
            "autogenerated": false, 
            "allowed_choices": [
                "RD_PRIMARY2", 
                "RD_PRIMARY1", 
                "RD_SECONDARY1", 
                "RD_SECONDARY2"
            ], 
            "availability": null, 
            "default_value": null, 
            "default_order": false, 
            "filterable": false, 
            "creation_only": false, 
            "max_length": null, 
            "orderable": false, 
            "type": "enum", 
            "channel": null, 
            "read_only": false, 
            "allowed_chars": null, 
            "description": "Indicates the uplink type associated with the instance of Uplink Route Distinguisher.  Default value is RD Primary1 Possible values are RD_PRIMARY1, RD_PRIMARY2, RD_SECONDARY1, RD_SECONDARY2, .", 
            "format": null, 
            "max_value": null, 
            "min_value": null, 
            "transient": false, 
            "unique": false, 
            "min_length": null, 
            "required": false
        }
    }, 
    "get": true, 
    "children": {}
}