{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": [
                "PRIMARY",
                "SECONDARY",
                "TERTIARY",
                "UNKNOWN"
            ],
            "autogenerated": false,
            "channel": null,
            "creation_only": false,
            "default_order": false,
            "default_value": "PRIMARY",
            "deprecated": false,
            "description": "To allow prioritisation of traffic, the NSG network ports must be configured with an uplink type or tag value which will be used in the identification of packets being forwarded.  That identification is at the base of the selection of which network port will serve in sending packets to the outside world.  The default value is PRIMARY. Possible values are PRIMARY, SECONDARY, TERTIARY, UNKNOWN, ",
            "exposed": true,
            "filterable": true,
            "format": null,
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "name": "tag",
            "orderable": true,
            "read_only": false,
            "required": false,
            "subtype": null,
            "transient": false,
            "type": "enum",
            "unique": false,
            "uniqueScope": null
        }
    ],
    "children": [],
    "model": {
        "create": null,
        "delete": true,
        "description": null,
        "entity_name": "UplinkConnection",
        "extends": [],
        "get": true,
        "package": null,
        "resource_name": "uplinkconnections",
        "rest_name": "uplinkconnection",
        "root": null,
        "update": true
    }
}